'use client';
import { useMemo, useState } from 'react';
type Row = { id: string; code: string; label: string; section: string; parent_id: string | null; is_active: boolean };
export function MockTaxonomyManager({ initialRows }: { initialRows: Row[] }) {
  const [rows, setRows] = useState(initialRows); const [label, setLabel] = useState(''); const [section, setSection] = useState('quant'); const [parentId, setParentId] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const roots = useMemo(() => rows.filter((row) => !row.parent_id && row.is_active), [rows]);
  async function call(body: Record<string, unknown>) { const response = await fetch('/api/admin/mock-taxonomy', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Taxonomy request failed.'); return data.taxonomy as Row; }
  async function create(parent: string | null) { setBusy(true); try { const value = await call({ action: 'create', label, section, parentId: parent }); setRows((current) => [...current, value]); setLabel(''); setParentId(''); setMessage(`${parent ? 'Subtopic' : 'Topic'} created.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Taxonomy request failed.'); } finally { setBusy(false); } }
  async function update(row: Row, next: { label?: string; isActive?: boolean }) { setBusy(true); try { const value = await call({ action: 'update', id: row.id, ...next }); setRows((current) => current.map((item) => item.id === row.id ? { ...item, ...value } : item)); setMessage('Taxonomy updated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Taxonomy update failed.'); } finally { setBusy(false); } }
  return <section className="admin-card mock-workspace-card" id="taxonomy-management" aria-labelledby="taxonomy-title"><div className="admin-card-header"><div><h2 className="admin-card-title" id="taxonomy-title">Taxonomy Management</h2><p className="admin-page-subtitle">Canonical topics and subtopics used by manual entry and bulk validation. Deactivation is reversible; referenced values cannot be deleted.</p></div><span className="badge badge-available">Admin only</span></div><div className="mock-form-grid"><label className="mock-field"><span>Label</span><input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="e.g. Divisibility and factors" /></label><label className="mock-field"><span>Section</span><select value={section} onChange={(event) => { setSection(event.target.value); setParentId(''); }}><option value="quant">Quant</option><option value="verbal">Verbal</option><option value="data_insights">Data Insights</option></select></label><label className="mock-field"><span>Parent topic (optional)</span><select value={parentId} onChange={(event) => setParentId(event.target.value)}><option value="">Create root topic</option>{roots.filter((row) => row.section === section).map((row) => <option key={row.id} value={row.id}>{row.label}</option>)}</select></label><button className="btn btn-primary" disabled={busy || !label.trim()} onClick={() => void create(parentId || null)}>{parentId ? 'Create subtopic' : 'Create topic'}</button></div><div className="mock-question-list">{rows.map((row) => <div className="mock-question-row" key={row.id}><span><strong>{row.parent_id ? '↳ ' : ''}{row.label}</strong><small>{row.section} · {row.is_active ? 'active' : 'inactive'} · {row.code}</small></span><button className="btn btn-secondary btn-sm" disabled={busy} onClick={() => { const next = window.prompt('Rename taxonomy value', row.label); if (next && next.trim() !== row.label) void update(row, { label: next.trim() }); }}>Rename</button><button className="btn btn-secondary btn-sm" disabled={busy} onClick={() => void update(row, { isActive: !row.is_active })}>{row.is_active ? 'Deactivate' : 'Activate'}</button></div>)}</div>{message && <p className="mock-status" role="status">{message}</p>}</section>;
}
